### ISSUE TITLE
Enable existing cloud integration via targets

### ISSUE THREAD

**Issue by wlandau** [ropensci/stantargets#38]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/stantargets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/stantargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

From @mbjoseph in #37: `tar_stan_mcmc()` etc. have no exposed `format` argument, so cloud storage is not supported. On the other hand, we don't want to completely expose formats because we want to make efficient choices for several targets automatically on behalf of the user. So we could support a simplified abstraction that chooses to store locally or to a cloud provider (currently only AWS S3).

**Comment by wlandau** [comment]
On second thought, I think we should just expose the format arguments.

**Comment by wlandau** [comment]
Should be fixed now. All target factories except `tar_stan_compile()` should have arguments `format` and/or `format_df` which allow you to select AWS-backed storage.

**Comment by mbjoseph** [comment]
Awesome - thanks Will!
