### ISSUE TITLE
pkgdown site build error

### ISSUE THREAD

**Issue by wlandau** [ropensci/stantargets#47]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/stantargets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in `stantargets` and not a known limitation, usage error, or bug in another package that `stantargets` depends on.
* [x] If there is [already a relevant issue](https://github.com/ropensci/stantargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [N/A] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [N/A] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [N/A] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [N/A] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

The `pkgdown` site of `stantargets` appears to have trouble building in Jenkins: https://dev.ropensci.org/blue/organizations/jenkins/stantargets/detail/stantargets/55/pipeline. @jeroen, anything in particular I should fix on my end?

**Comment by jeroen** [comment]
Hi sorry for the late response. 

We have migrated the docs build system from jenkins to r-universe: https://ropensci.org/blog/2021/09/03/runiverse-docs/

As far as I can see, stantargets seems to work: https://github.com/r-universe/ropensci/actions/runs/1187750177

**Comment by wlandau** [comment]
Thanks, @jeroen. The migration to r-universe is exciting.
