### ISSUE TITLE
Expose .cores argument for summary

### ISSUE THREAD

**Issue by stuvet** [ropensci/stantargets#52]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/stantargets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/stantargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

`posterior::summarise_draws` has a `.cores` option which offers big speedups for summarising larger posteriors. Currently it is not accessible via `summary_args`.

It'd be very helpful to expose a `summary_cores` option to `tar_stan_summary` and `tar_stan_mcmc`, which could default to `1` to match `posterior::summarise_draws` defaults. In [my fork](https://github.com/ropensci/stantargets/compare/main...define-ag:stantargets:summary-cores) I've included `parallel::detectCores` triggered by `summary_cores = NULL`. I was half way through submitting it as a PR, but saw the prework so raised here first. Currently tested with `tar_make_future` on slurm (need to set appropriate `ncpus` in the _default_ resources if called from `tar_stan_mcmc`).  

Happy to submit it as a PR if you'd like, but you may forsee problems that I can't.

Thanks

**Comment by wlandau** [comment]
Sounds great to me. Would you open a PR? Would be great to have summary_cores argument wherever there is summary_args, which includes the gq, mle, and vb functions as well as the mcmc ones.

**Comment by stuvet** [comment]
Ah yes, I didn't think about the other options, but I'm just starting to use `gq` & it'll be very welcome here too. I'll add them all & submit in a sec.

**Comment by wlandau** [comment]
@stuvet, I actually think you can supply the number of cores to the `summary_args` argument, e.g. `tar_stan_mcmc_rep_summary(..., summary_args = list(.cores = 4))`. The `summary_args` argument populates the `...` argument of the [`summary()` method](https://mc-stan.org/cmdstanr/reference/fit-method-summary.html) of `CmdStanFit` objects, which then gets forwarded to [posterior::summarize_draws()](https://mc-stan.org/posterior/reference/draws_summary.html).
