### ISSUE TITLE
R Markdown error pkgdown

### ISSUE THREAD

**Issue by maelle** [ropensci/stantargets#62]
From https://ropensci.r-universe.dev/builds

I have nothing more specific than

```
 Quitting from lines 434-435 [unnamed-chunk-27] (introduction.Rmd)
--------------------------------------------------------------------------------
---
```

Does it ring a bell? :sweat_smile: If not happy to help investigate.

**Comment by wlandau** [comment]
Thanks, just needed to update the included Stan models to use the new array syntax.
